services:
  api:
    user: root
    container_name: mice_kazan_api
    build:
      context: .
      dockerfile: WebApp1/Dockerfile
    ports:
      - "192.168.0.105:4444:8080"
    environment:
      - HTTP_PORTS=8080
    env_file: .env
    volumes:
      - api:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db
  print:
    user: root
    container_name: mice_kazan_print
    build:
      context: .
      dockerfile: Micekazan.PrintDispatcher/Dockerfile
    ports:
      - 8081:8080
    environment:
      - HTTP_PORTS=8080
    env_file: .env
    volumes:
      - print:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db
  db:
    container_name: mice_kazan_db
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - 6432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    name: mice_kazan_db
  api:
    name: mice_kazan_api
  print:
    name: mice_kazan_print
